### PR TITLE
updated install.sh and added instructions

### PR DESCRIPTION
**Pull request by jclc**

### CODE REVIEW

**Comment by juvester** [comment]
The URL in install.sh is fixed to release 0.6.3.

Would something like this work: http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo#comment49193423_26738019

**Comment by Salmela** [comment]
@juvester The json parsing solution won't work, because it's nearly impossible to parse json in bash without additional dependencies. The fixed version number isn't really problem, because user is immediately asked, if they want to update  to the newer version.

Edit: The curl line is really interesting and it could work if we always put the tmc binary as first asset in the releases or if we replace the filename of the first download url with the binary's name aka. `tmc`.

Edit2: This could work
`curl -s https://api.github.com/repos/tmc-cli/tmc-cli/releases | grep -e '"browser_download_url".*/tmc"' | head -n 1 | cut -d '"' -f 4`

Edit3: the `#comment49193423_26738019` part of your link didn't work but I found the comment from the source code and it's solution would be probably cleanest.

**Comment by jclc** [comment]
@Salmela Would the command in Edit2 also return pre-releases?

**Comment by Salmela** [comment]
Yeah. I didn't take the pre-releases into account. But it's easy to fix because the latest release is never pre-release so the below line would work.

`curl -s https://api.github.com/repos/tmc-cli/tmc-cli/releases/latest | grep -e '"browser_download_url".*/tmc"' | head -n 1 | cut -d '"' -f 4`

or this which is bit nicer and simpler code from @juvester 's comment

`curl -s https://api.github.com/repos/tmc-cli/tmc-cli/releases/latest  | grep '"browser_download_url"' | grep '/tmc"' | head -n 1 | cut -d '"' -f 4`

**Comment by Salmela** [comment]
BTW @jclc could you merge my #376 pull request and create release.

I fixed again a bug from the launch script that had to do with auto-update. I am bit tired of numerous bugs in the bash scripts so I already created a stub for script unit tests.

I am not available or doing any changes for about a week.

**Comment by jclc** [comment]
Install script should work fine now.

**Comment by Salmela** [comment]
LGTM.

[Approved with PullApprove](https://pullapprove.com/tmc-cli/tmc-cli/pull-request/377/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=tmc-cli/tmc-cli)

**Pull request merged**
